### ISSUE TITLE
Question: initiating quick filter

### ISSUE THREAD

**Issue by alexjpujol** [ceolter/ag-grid-ng2-example#11]
How does one include the quick filter (the text search filter in the top corner)? I've included the following: 

private onQuickFilterChanged($event) {
        this.gridOptions.api.setQuickFilter($event.target.value);
}

but it doesn't appear to initiate the filter. Any ideas? Thanks

**Comment by ceolter** [comment]
what you have should be working. try debugging through your code. my suspicion is $event.target.value is not correct, as you have the right api call and should otherwise be working.
