### ISSUE TITLE
Does not compile due to rc6 release

### ISSUE THREAD

**Issue by kbdguy** [ceolter/ag-grid-ng2-example#13]
work-around: before running npm install, edit package.json and remove the "~" from all of the @angular dependency version specs.

**Comment by kbdguy** [comment]
also... I tried refactoring to use app.module.ts with angular2.rc6, and had no luck getting AgComponentFactory injected (in FromRichComponent).  Theoretically, I should be able to put AgComponentFactory in the "providers" section of the @NgModule decorator, and take it out of the @Component decorator.  Had no luck due to errors displayed in console.  First: "No provider for ViewContainerRef!", and then when I tried adding ViewContainerRef to the "providers" section of @NgModule: "Error: Uncaught (in promise): unimplemented".  I also tried without explicit ViewContainerRef in FromRichComponent constructor, with no better result.  

Since using directive in the @Component decorator in angular2.rc6 raises an error, we are stuck in rc5 for now, I think.

**Comment by yparenteau** [comment]
Any idea when it will be supported rc6?

**Comment by seanlandsman** [comment]
We have updated this to work with rc6 - we'll be releasing this shortly

**Comment by seanlandsman** [comment]
this has now been released - 5.3.2
