### ISSUE TITLE
Missing AgEditorAware in ag-grid-ng2/main

### ISSUE THREAD

**Issue by Emilion** [ceolter/ag-grid-ng2-example#14]
Hello,

I tried to start the ag-grid-ng2-example following the steps described in Readme.md, but AgEditorAware is missing. I am using **node** : 6.2.2 and **npm** : 3.10.6

Here is the row with the error 
`/ag-grid-ng2-example/node_modules/ag-grid-ng2/main"' has no exported member 'AgEditorAware'.`

Did I miss something to do?

Thanks in advance

Regards,
Emil Kopev

**Comment by seanlandsman** [comment]
Hi,

We're in the process of adding new functionality and refactoring at the same time. If you want to try this out from master you'll need to checkout ag-grid-ng2 and reference this in package.json (ie "ag-grid-ng2": "file:../ag-grid-ng2",, but please be aware that there are likely to be many changes over this week.

If you're just after the stable release of ng2 (and the examples), then please checkout the last release of both (5.4.0) - not the latest from master.

I hope this helps

**Comment by Emilion** [comment]
Hi @seanlandsman ,

Sorry for the late answer. 
Yes it helps. 
I am waiting for the incoming changes and new features.

Regards
