### ISSUE TITLE
Trying to load RC4 version

### ISSUE THREAD

**Issue by jestersimpps** [ceolter/ag-grid-ng2-example#15]
Hi, Our company is interested in implementing the enterprise version in our angular 2 RC4 application. Since there is no release for angular 2 - RC4, I went through the commits and implemented versions:
 
    "ag-grid": "5.1.x",
    "ag-grid-enterprise": "5.1.x",
    "ag-grid-ng2": "5.1.x",

1) The core grid works ok, however, input fields seem a bit slow compared to the example version : https://www.ag-grid.com/example.php

2) When I'm trying to activate the enterprise version (by importing the 'ag-grid-enterprise/main') I am getting the following error:
context.js:185ag-Grid: unable to find bean reference pivotService while initialising AggregationStage;

I'm a bit stuck at the moment as upgrading our project to RC6 is not an option. We have other dependencies that are at RC4.

**Comment by seanlandsman** [comment]
Hi,

I'm sorry, but I'm not sure we'll be able to help you here - we're currently in the process of a major release which will include support for RC7. (and full editor, renderer etc component support) 

I don't think its possible for us to support RC4 anymore. That said, your error doesnt sound like a ng specific problem - have you tried just using the enterprise features (as a test) without ng2? Does that work?

**Comment by jestersimpps** [comment]
I understand. We will probably do the upgrade later. I played around a bit with the versions and  discovered that the following combination works for RC4:

    "ag-grid": "5.1.x",
    "ag-grid-enterprise": "5.3.x",
    "ag-grid-ng2": "5.1.x",

(just in case other people are using ag-grid with RC4)

**Comment by ceolter** [comment]
if you are not using ng2 cellRenderers or cellEditors, you could just drop the ng2 part of ag-Grid. I mean, use the plain JavaScript version of ag-Grid inside your app. just a thought.

**Comment by jestersimpps** [comment]
Thanks for the suggestion. Will look into that if I run into any other issues for sure. Since angular 2.0.0 is out now, will ag-grid support the 2.0.0 instead of the RC7 version? If so, do you have an estimate as to when this major overhaul would be ready?

**Comment by seanlandsman** [comment]
Hi

Version 6.0.2 of ag-grid-ng (and ag-grid-ng2-examples) supports 2.0.0

thanks
