### ISSUE TITLE
Missing AgRendererComponent in ag-grid-ng2/main

### ISSUE THREAD

**Issue by sameerbag** [ceolter/ag-grid-ng2-example#16]
Getting error : "has no exported member 'AgRendererComponent'"

**Comment by seanlandsman** [comment]
If you wish to wish to build from master, then you need to pull in both ag-grid and ag-grid-ng (also from master), and reference each other (ie via file:..)

Alternatively we'll be releasing 6.x today, after which this particular issue will be resolved.

**Comment by seanlandsman** [comment]
Release 6.0.1 should fix this issue
