### ISSUE TITLE
Does not compile from fresh clone - no exported member 'AgFilterComponent' in main

### ISSUE THREAD

**Issue by aryeh** [ceolter/ag-grid-ng2-example#17]
app/filter-component.component.ts(5,9): error TS2305: Module '"/opt/ngdev/tmp/ag-grid-ng2-example/node_modules/ag-grid-ng2/main"' has no exported member 'AgFilterComponent'

**Comment by aryeh** [comment]
Fixed. Thank you.

**Comment by Mosesgithub** [comment]
I am having the similar issue. Instead 'as no exported member 'AgFilterComponent'' it is as no exported member 'TooltipParams'
