### ISSUE TITLE
Error in app/rich-grid.component.html:77:21 caused by: Cannot read property '$new' of null

### ISSUE THREAD

**Issue by sameerbag** [ceolter/ag-grid-ng2-example#18]
I am getting this error when I set the angularCompileRows to gridOption in rich-grid-component.

**Comment by seanlandsman** [comment]
that option is for angular1 - it doesnt apply for angular components.

Please see https://www.ag-grid.com/best-angularjs-data-grid/index.php for angular 1 usage, or https://www.ag-grid.com/best-angular-2-data-grid/index.php for angular 2
