### ISSUE TITLE
Button in cell

### ISSUE THREAD

**Issue by pantonis** [ceolter/ag-grid-ng2-example#2]
Hi.

How do I add a delete/edit button in a column?

Thanks

**Comment by ceolter** [comment]
use a cellRenderer

**Comment by ceolter** [comment]
but it cannot be angular 2, see the note on angular 2 compiling here:
https://www.ag-grid.com/best-angular-2-data-grid/index.php

**Comment by pantonis** [comment]
Okie.

I am using `gridOptions.columnApi.autoSizeColumns(allColumnIds);` on the onReady event.
Problem is that data are not loaded at the time onReady is fired (async http request) and the width of the columns is set to 10px; 

Is there any event to indicate when data binding has finished?

**Comment by zngong** [comment]
how to add click event to this button?

**Comment by Yuvamac** [comment]
Using cellRenderer in ag-grid how to fire a click event in angular5
cellRenderer  : (params)=> {return <span (click)="kick()">Kick Me</span>}

kick() { alert ('Kicked') }
i can't able to fire a click event in cellRenderer any suggestion ??

Thanks
