### ISSUE TITLE
Not able to populate grid with data. Data is saved in rowData fine.

### ISSUE THREAD

**Issue by kapoorruchi** [ceolter/ag-grid-ng2-example#21]
I'm not able to populate grid with my data. Data is just fine, however divs are not populating.
<ag-grid-ng2 #agGrid style="height: 100%; width:100% ; border: 10px solid green;" class="ag-fresh"
      [gridOptions]= "gridOptions"  [columnDefs]="columnDefs" [rowData] = "rowData">
</ag-grid-ng2>

 this.columnDefs = [
            { headerName: "ID", field: "id", hide: false, width: 68 },
            { headerName: "FIRSTNAME", field: "firstname", width: 320 }
        ];

gridOptions: GridOptions = <GridOptions>{};
 private createRowData() {
         var rowData: any[] = [];
        rowData.push({ id : 1, firstname : "test"});
        rowData.push({ id : 2, firstname : "you"});
        this.rowData = rowData;
    }

**Comment by seanlandsman** [comment]
Theres no reason what you have shouldnt work - can you please provide a plunker, or your full code for me to investigate

**Comment by olegkon** [comment]
Hi,
I have a similar issue.
Can someone tell me how to Refresh ag-grid in Angular2?I am working on a sample, and it shows it initially with fake data,but when real data arrives, I try to call on subscribe() 1st param:(weather: WeatherResult) => {
    this.weather = weather;
    this.gridOptions.rowData = this.createDGRowData(weather);
    this.gridOptions.api.refreshView();   <==  Refresh grid is not happening
    console.log(this.gridOptions.rowData);  <== see correct data...
},... Any idea how to refresh the grid correctly in Ang2  ?

Thank you in advance, Oleg. 

    On Tuesday, October 18, 2016 9:18 AM, seanlandsman <notifications@github.com> wrote:
 

 Theres no reason what you have shouldnt work - can you please provide a plunker, or your full code for me to investigate—

**Comment by seanlandsman** [comment]
Hi @olegkon ,

gridOptions.rowData is read once off when the grid is created - if you set rowData to some value (say an empty array, or default data), then change it it wont update.

You have two options here:

- Leave gridOptions.rowData undefined and set it when you get your data: this will display a "Loading" message until the data is set
- Use gridOptions.setRowData when you receive your data - this can be called repeatedly and will refresh the grid contents with the new data

**Comment by olegkon** [comment]
I tried second option:  this.gridOptions.setRowData(this.createDGRowData(weather));WebStorm showed error: property setRowData doesn't exist on type GridOptions.  Thank you,  Oleg. 

    On Wednesday, October 19, 2016 2:09 AM, seanlandsman <notifications@github.com> wrote:
 

 Hi @olegkon ,gridOptions.rowData is read once off when the grid is created - if you set rowData to some value (say an empty array, or default data), then change it it wont update.You have two options here:   
   - Leave gridOptions.rowData undefined and set it when you get your data: this will display a "Loading" message until the data is set
   - Use gridOptions.setRowData when you receive your data - this can be called repeatedly and will refresh the grid contents with the new data

**Comment by seanlandsman** [comment]
Apologies - gridOptions.api.setRowData - I missed the .api. bit

**Comment by seanlandsman** [comment]
Closing this now - please raise a new issue (or reopen this one) if this is still a problem for you

**Comment by pdvbalaji** [comment]
HI,
Data is coming from data and also getting to rowdata ,but not bind 
below is my code , Only headers and displaying , please help 
private loadGrid(GridData: any[]) {
        this.gridOptions = null;
        setTimeout(() => {
            debugger;
            this.gridOptions = <GridOptions>{}; 
             
             this.gridOptions.rowData = this.GridData;
           // this.gridOptions.api.setRowData(this.gridOptions.rowData);
            if (this.gridOptions.rowData.length > 0) this.displayFilter = false;
            this.gridOptions.columnDefs = this.createColumnDefs();
            this.gridOptions.api.sizeColumnsToFit();
           
            this.gridOptions.api.getEditingCells();
            this.gridOptions.enableFilter = true;
            this.gridOptions.enableSorting = true;
        });
    }

**Comment by aburht** [comment]
I'm having same issue

**Comment by AMehraCriteo** [comment]
I am facing the same issue after going from v7 to v11 in Angular. No errors, rowData is set in the class file but the ag-grid renders empty. Was a solution figured out?

**Comment by mayank-prakash-nit-jsr** [comment]
When I fetch data from api then ag grid completely blank and headers also not there but when I put same data as static then it populates and render completely fine. Is anyone facing same issue ? Why this is happening any solutions for this?

**Comment by StephenCooper** [comment]
Please open a new issue with a code sample showing your issue. Without this we cannot help you effectively.

**Comment by mayank-prakash-nit-jsr** [comment]
> Please open a new issue with a code sample showing your issue. Without this we cannot help you effectively.

Thanks for replying. I have created a new issue.
