### ISSUE TITLE
how to create pagination

### ISSUE THREAD

**Issue by rahulscp** [ceolter/ag-grid-ng2-example#22]
i tried with rowModelType="pagination".
but it showing no records bt the pagination buttons.

any help to implement it properly or any example is much appreciated

**Comment by ceolter** [comment]
examples are here:
https://www.ag-grid.com/javascript-grid-pagination/

**Comment by rahulscp** [comment]
is there any example in angualr 2 ? how do i create pagination for static data

**Comment by ceolter** [comment]
no - the examples for all the features are given in plain javascript, so anyone can understand them regardless off what framework they are doing. we don't have a team big enough to give examples in all the frameworks that we are supporting.

the ng2 examples explain how to use the grid in ng2 - but for the specific features you need to go to the standard examples and know how to set them up using angualar 2 properties etc.
