### ISSUE TITLE
crud examle required

### ISSUE THREAD

**Issue by rahulscp** [ceolter/ag-grid-ng2-example#23]
it will be reallly helpful if u add example for a crud operation in ag-grid.

Thanks,

**Comment by seanlandsman** [comment]
Can you elaborate? What sort off use case did you have in mind? Read on load perhaps, then write as data is updated, or via a button?

**Comment by rahulscp** [comment]
thanks for the quick response. what i am expecting is a grid with row editing with an popup form, deleting row and adding new row with a popup form

**Comment by seanlandsman** [comment]
hi @rahulscp I'm afraid we wont be able to provide an example like this - partly as it isnt a grid responsbility, but party too because its just too open ended and depends wildly on your persistence framework/target
