### ISSUE TITLE
Won't build

### ISSUE THREAD

**Issue by wujitouch** [ceolter/ag-grid-ng2-example#28]
I get this error when running npm run tsc

node_modules/ag-grid-ng2/dist/ng2FrameworkFactory.d.ts(4,22): error TS2420: Class 'Ng2FrameworkFactory' incorrectly implements interface 'IFrameworkFactory'.
  Types of property 'setTimeout' are incompatible.
    Type '(action: any, timeout?: any) => void' is not assignable to type '(handler: any, timeout?: any) => number'.
      Type 'void' is not assignable to type 'number'.
node_modules/ag-grid/main.d.ts(12,15): error TS2307: Cannot find module './dist/lib/context/beanStub'.
node_modules/ag-grid/main.d.ts(37,15): error TS2307: Cannot find module './dist/lib/gridPanel/scrollVisibleService'.

I have the following 3 folders in the same directory and am trying to build the example inside the example folder:

ag-grid
ag-grid-ng2
ag-grid-ng2-example

**Comment by seanlandsman** [comment]
master is generally subject to regular changes and is often (as in this case) dependent on changes to master in ag-grid or ag-grid-enterprise.
We are about to do a new release later today, which will bring ag-grid and ag-grid-ng2 into line once again.

As a temporary fix, alter 

node_modules/ag-grid/dist/lib/interfaces/iFrameworkFactory.d.ts and change the return type of setTimeout to void

And in node_modules/ag-grid/main.d.ts delete the lines with beanStub and scrollVisibleService from them

As I say this is only temporary - from tomorrow you won't need to do this

**Comment by seanlandsman** [comment]
I realise that theres actually another problem here - I mistakenly checked in package.json with local only changes. I've corrected this - do an update, clear down node_modules, npm i once again and retry. It should work fine now
