### ISSUE TITLE
Data bound event

### ISSUE THREAD

**Issue by pantonis** [ceolter/ag-grid-ng2-example#3]
I am using gridOptions.columnApi.autoSizeColumns(allColumnIds); on the onReady event.
Problem is that data are not loaded at the time onReady is fired (async http request) and the width of the columns is set to 10px;

Is there any event to indicate when data binding has finished?

**Comment by ceolter** [comment]
are you using the api or a property to set the row data?

if api, then call autoSizeColumns after you call setRowData, the rowData is not rendered asynchronously, so when setRowData returns, the rows are rendered.

if you are using a property, then i don't know, as processing of the property and passing the result to the grid is not in my control. maybe put it in a timeout after you set the property.

**Comment by pantonis** [comment]
what would be the ideal timeout?

**Comment by ceolter** [comment]
try zero.

all that might be needed is the JavaScript turn to complete.


On 7 March 2016 at 10:07, pantonis <notifications@github.com> wrote:

> what would be the ideal timeout?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/ag-grid-ng2-example/issues/3#issuecomment-193189133>
> .
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by pantonis** [comment]
thanks.
