### ISSUE TITLE
Webpack npm install failing at postinstall script './node_modules/protractor/bin/webdriver-manager update'.

### ISSUE THREAD

**Issue by mholland231** [ceolter/ag-grid-ng2-example#30]
I cloned from your repo and tried to build the webpack directory but am running into the below issue. I updated node and npm to the latest versions and am still encountering this issue. I included my npm log below. Have you seen this before? I know the webpack config is only a couple of weeks old. 

[npm-debug.log.txt](https://github.com/ceolter/ag-grid-ng2-example/files/685809/npm-debug.log.txt)

c:\dev\ag-grid-ng2-example\webpack>npm install

> ag-grid-ng2-example@7.1.0 postinstall c:\dev\ag-grid-ng2-example\webpack
> ./node_modules/protractor/bin/webdriver-manager update

'.' is not recognized as an internal or external command,
operable program or batch file.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"
})

npm WARN ag-grid-ng2@7.1.1 requires a peer of zone.js@^0.6.x but none was instal
led.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mholland231\\AppData
\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! ag-grid-ng2-example@7.1.0 postinstall: `./node_modules/protractor/bin/w
ebdriver-manager update`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ag-grid-ng2-example@7.1.0 postinstall script './node_modu
les/protractor/bin/webdriver-manager update'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ag-grid-ng2-example p
ackage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./node_modules/protractor/bin/webdriver-manager update
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ag-grid-ng2-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ag-grid-ng2-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\vsetdev\ag-grid-ng2-example\webpack\npm-debug.log

**Comment by twbutler** [comment]
I am trying the systemjs_aot project, and see very similar failures there also.  It does not appear to be confined to just the webpack. 

[npm-debug.log.txt](https://github.com/ceolter/ag-grid-ng2-example/files/685949/npm-debug.log.txt)

$ npm install
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN lifecycle The node binary used for scripts is C:\Program Files (x86)\Nodist\bin\node.exe but npm is using C:\Program Files (x86)\Nodist\v-x64\7.4.0\node.exe itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> ag-grid-ng2-example@7.1.0 postinstall C:\Users\trbutl\git\ag-grid-ng2-example\systemjs_aot
> ./node_modules/protractor/bin/webdriver-manager update

'.' is not recognized as an internal or external command,
operable program or batch file.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.16: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN ag-grid-ng2@7.1.1 requires a peer of zone.js@^0.6.x but none was installed.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\Nodist\\v-x64\\7.4.0\\node.exe" "C:\\Program Files (x86)\\Nodist\\npmv\\4.1.1\\bin\\npm-cli.js" "install"
npm ERR! node v7.4.0
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE
npm ERR! ag-grid-ng2-example@7.1.0 postinstall: `./node_modules/protractor/bin/webdriver-manager update`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ag-grid-ng2-example@7.1.0 postinstall script './node_modules/protractor/bin/webdriver-manager update'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ag-grid-ng2-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./node_modules/protractor/bin/webdriver-manager update
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ag-grid-ng2-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ag-grid-ng2-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\trbutl\git\ag-grid-ng2-example\systemjs_aot\npm-debug.log

**Comment by seanlandsman** [comment]
I think I see the problem here - in both your cases you're on windows but the postinstall is using *nix paths.

I'll have a look and correct this

**Comment by seanlandsman** [comment]
@mholland231 @twbutler I've pushed a fix for this - can you please update and retry?

**Comment by mholland231** [comment]
I did a pull. The project now builds without issue. Thanks for the fix!

**Comment by twbutler** [comment]
I pulled and then re-ran npm install...  It now works for me also!
Thanks!
