### ISSUE TITLE
Compiler Issue on Using ag-grid with Angular 2.3.0

### ISSUE THREAD

**Issue by usersk12** [ceolter/ag-grid-ng2-example#31]
I'm facing following issue on updating Angular version to 2.3.0 from 2.1.2 in my application:

ERROR in [default] F:\Projects]\FrontEnd\node_modules\ag-grid-ng2\lib\ng2ComponentFactory.d.ts:3:9 Module '"F:/[Projects]/FrontEnd/node_modules/@angular/compiler/index"' has no exported member 'RuntimeCompiler'.

Kindly provide help with above issue. ag-grid and ag-grid-ng2 version used is 6.2.0.

**Comment by seanlandsman** [comment]
6.x is not compatible with 2.3 - angular dropped/moved the RuntimeCompiler in 2.2 I think. You'll need to upgrade to 7.x to use 2.3+.

Please see https://www.ag-grid.com/best-angular-2-data-grid/ for more information, as there were some breaking changes between 6.x and 7.x
