### ISSUE TITLE
How  to display the Header and data row by two row each?

### ISSUE THREAD

**Issue by usersk12** [ceolter/ag-grid-ng2-example#32]
I want to display the header and data row in the following way using ag-grid in our angular2/typescript application:
suppose the grid contain the data in the following format:

Header1  | Header2 |  Header3 |
data1      | data2      |  data3      |

After resizing the screen on browser the grid should be like this:

Header1  | Header2 | 
Header3  |
data1       | data2      |
data3       |

Has ag-grid provide any these type feature?
Currently when we are resizing the screen on browser the column size resize. the Header doesn't come in the next row.

**Comment by seanlandsman** [comment]
hi - no, we dont offer wrapping of columns.

For more than one row of data this just wouldnt work I'm afraid
