### ISSUE TITLE
how to display 1 data in 2 lines?

### ISSUE THREAD

**Issue by usersk12** [ceolter/ag-grid-ng2-example#33]
I want to display of 1 data in 2 line in a following ways.

Header1|header2|
Header3| Header4|
data1 | data2|
data3| data4|

in issue #32 I have created the issue but where I have ask for the resizing on browser.
But here instead of resizing the browser we want to put the 1 row data in 2 line in the grid.
Please let us know if these feature is available or not?

**Comment by seanlandsman** [comment]
Hi 

Please post support questions either on our free forum (https://ag-grid.com/forum) or on stackoverflow. GitHub should be reserved for issues in the code if possible.

In answer to your question I'm afraid we don't support what you're after here. As with the other issue, how would this work if there was more than 1 row of data?

That aside though, you could have part of the header in the normal header location, with the rest as a floating row at the top (https://www.ag-grid.com/javascript-grid-floating/)

For the data itself you would have to pre-process it and split the data across two rows
