### ISSUE TITLE
npm start crashes

### ISSUE THREAD

**Issue by trium4** [ceolter/ag-grid-ng2-example#34]
Hello,
your current angular-cli example crashes for me on Win10/64Bit.

Do you have any solution for me?
Many thanks.
@trium4
[npm-debug.log.txt](https://github.com/ceolter/ag-grid-ng2-example/files/706760/npm-debug.log.txt)
[mylog.stdout.txt](https://github.com/ceolter/ag-grid-ng2-example/files/706761/mylog.stdout.txt)
[mylog.stderr.txt](https://github.com/ceolter/ag-grid-ng2-example/files/706762/mylog.stderr.txt)

**Comment by seanlandsman** [comment]
hi - we can't reproduce this here, on either osx or windows 10.

Have you installed all the npm dependencies?

**Comment by seanlandsman** [comment]
Closing as cannot reproduce
