### ISSUE TITLE
Radio Button not rendered properly in ag-grid

### ISSUE THREAD

**Issue by usersk12** [ceolter/ag-grid-ng2-example#35]
I've written following code in my application to render radio button in ag-grid. Radio button is appearing properly.

        public radioCellRenderer(param: any) {
            let eCell = document.createElement("input");
            eCell.type = "radio";
            eCell.name = "radioButton";
            eCell.value = param.node.data.radio;
    
            eCell.addEventListener("change", function (ev) {
                ...
            });
            return eCell;
        }
    
        public gridOptions {... columnDefs:  {
        headerName: "Select",
        field: "radio",
        cellRenderer: this.radioCellRenderer,
        // pinned: true
    },}

The grid width is larger and there is scroll bar appearing in grid. If I select the radio button, it is selected. When I scroll horizontally in the grid to view other columns and scroll back, then radio button gets deselected.

Kindly provide help with above issue.

**Comment by seanlandsman** [comment]
Renderers & Components by default are destroyed when no longer visible, and recreated when visible again.

You have two options here - either save the change to the grid when a radio button is selected or suppress column virtualisation (suppressColumnVirtualisation = true)

Note that if you suppress column virtualisation then grid performance can suffer depending on the size of your data

**Comment by usersk12** [comment]
Thanks for sharing the information. 
The suppressColumnVirtualisation is working perfectly. But as there can be performance issue on large data. so we want to implement on the basis of second option.
"Save the changes to the grid when radio button selected"
How we can save these changes so that the radio button is in selected state when horizontal bar is scrolled back again?

**Comment by toooooshar** [comment]
[LATEST] Very Simple! (after you read below, hehe)

Step 1: In columnDefs: {checkboxSelection: false} // Add this to your object

Step 2: Add this to the same object where you added 'checkboxSelection' 

            cellRenderer: function cellTitle(params) {
				let cellValue = '<div class="ngSelectionCell"><input name="selected" type="radio"></div>';
				return cellValue;
			},

Step 3: Add this code to your local css file :

        .ag-body {
           .ag-row {
              .ag-cell {
                 input[type=checkbox]:checked:after, 
                 input[type=radio]:checked:after{
                 display: none;
                 }
                 input[type=checkbox]:after, input[type=radio]:after{
                  display: none;
                 }
              }
            }
          }`

Hope it helps you!

**Comment by tooshar** [comment]
[LATEST] Very Simple! (after you read below, hehe)

Step 1: In columnDefs: {checkboxSelection: false} // Add this to your object

Step 2: Add this to the same object where you added 'checkboxSelection' 

            cellRenderer: function cellTitle(params) {
				let cellValue = '<div class="ngSelectionCell"><input name="selected" type="radio"></div>';
				return cellValue;
			},

Step 3: Add this code to your local css file :

        .ag-body {
           .ag-row {
              .ag-cell {
                 input[type=checkbox]:checked:after, 
                 input[type=radio]:checked:after{
                 display: none;
                 }
                 input[type=checkbox]:after, input[type=radio]:after{
                  display: none;
                 }
              }
            }
          }`

Hope it helps you!

**Comment by swetarai763** [comment]
@tooshar 
Hi
I have applied this and radio button is rendering now.
But I need to autoselect first radio on load and on button click I need to send that row data
Please guide

**Comment by swetarai763** [comment]
> [LATEST] Very Simple! (after you read below, hehe)
> 
> Step 1: In columnDefs: {checkboxSelection: false} // Add this to your object
> 
> Step 2: Add this to the same object where you added 'checkboxSelection'
> 
> ```
>         cellRenderer: function cellTitle(params) {
> 			let cellValue = '<div class="ngSelectionCell"><input name="selected" type="radio"></div>';
> 			return cellValue;
> 		},
> ```
> 
> Step 3: Add this code to your local css file :
> 
> ```
>     .ag-body {
>        .ag-row {
>           .ag-cell {
>              input[type=checkbox]:checked:after, 
>              input[type=radio]:checked:after{
>              display: none;
>              }
>              input[type=checkbox]:after, input[type=radio]:after{
>               display: none;
>              }
>           }
>         }
>       }`
> ```
> 
> Hope it helps you!

Hi
I have applied this and radio button is rendering now.
But I need to autoselect first radio on load and on button click I need to send that row data
Please guide
