### ISSUE TITLE
Unable to call a function inside addEventListener

### ISSUE THREAD

**Issue by aachman** [ceolter/ag-grid-ng2-example#38]
headerName: "Show Details",
field: "ShowDetails",
cellRenderer: this.detailsRenderer

    public detailsRenderer(params: any) {
        let eDiv = document.createElement("div");
        eDiv.innerHTML = "<button type='button'> Show  </button>";
        eDiv.addEventListener("click", this.rowData);
        return eDiv;
    }

    public rowData(param: any) {   }

When calling a method inside addEventListener , then following error is shown at runtime that calling method is undefined.
How to resolve this.

**Comment by seanlandsman** [comment]
When your renderer is called this is no longer the scope of the gridOptions or containing method/class

To do what you're after try:

    cellRenderer: this.detailsRenderer.bind(this)
