### ISSUE TITLE
ag-grid does not work with latest Angular 2 Webpack(2) starter

### ISSUE THREAD

**Issue by shaikhspear16** [ceolter/ag-grid-ng2-example#43]
ag-grid does not work with latest angular 2 webpack starter kit. Unable to read module GridOptions. 
Please can you update the repo for using ag-grid with webpack

**Comment by seanlandsman** [comment]
hi - this is something I was planning on looking at this week I hope

**Comment by seanlandsman** [comment]
new webpack 2 example good to go

please note i'll be restructuring the layout of this this week to remove dupe'd code, but the examples will be the same, just slightly diff layout

**Comment by shaikhspear16** [comment]
That's great news... Thanks @seanlandsman. looking forward to the updates....  :+1:
