### ISSUE TITLE
filter trouble with server-side datasource

### ISSUE THREAD

**Issue by datumgeek** [ceolter/ag-grid-ng2-example#44]
i'm sure i'm doing something silly (or not doing something i should be)...  thanks in advance for any guidance you can provide.

here's a plunker that reproduces the behavior i'm seeing:
http://plnkr.co/edit/4d2bJswUnOcamW29mjWl?p=preview

when i apply a filter, the grid seems to reset to page 1 and forget the current filter...

before:

![image](https://cloud.githubusercontent.com/assets/22680176/22892479/f734d482-f1cf-11e6-8532-ef21c91738e9.png)

after:

![image](https://cloud.githubusercontent.com/assets/22680176/22892508/16a09900-f1d0-11e6-8dd7-3bbb9b4c5d4e.png)

you can see that hitting the apply button moved the grid back to the first page and also cleared the filter.

**Comment by datumgeek** [comment]
fixed it !!!!!!!!!!!! :smile:

updated plunker:
http://plnkr.co/edit/4d2bJswUnOcamW29mjWl?p=preview

**Comment by seanlandsman** [comment]
Good work :-) 👍
