### ISSUE TITLE
Not able to do npm install

### ISSUE THREAD

**Issue by pwd3** [ceolter/ag-grid-ng2-example#7]
I am getting an error on the first step in the README

I have a working npm and have other Angular2 projects that work without problem
BUT this is the first time I have tried the RC-1 (have been working on beta-15 and
beta-7)
I am getting:

npm http GET https://registry.npmjs.org/bootstrap
npm http GET https://registry.npmjs.org/lite-server
npm http GET https://registry.npmjs.org/concurrently
npm http GET https://registry.npmjs.org/es6-shim
npm http 404 https://registry.npmjs.org/angular/http/2.0.0-rc.1
npm http 404 https://registry.npmjs.org/angular/compiler/2.0.0-rc.1
npm ERR! 404 'angular' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.4.8-300.fc23.x86_64
npm ERR! command "node" "/bin/npm" "install"
npm ERR! cwd /home/pwd/src/ag-grid-ng2-example
npm ERR! node -v v0.10.42
npm ERR! npm -v 1.3.6
npm ERR! code E404
npm http 200 https://registry.npmjs.org/ag-grid-enterprise
npm http 404 https://registry.npmjs.org/angular/platform-browser/2.0.0-rc.1
npm http 404 https://registry.npmjs.org/angular/router/2.0.0-rc.1
npm http GET https://registry.npmjs.org/ag-grid-enterprise/-/ag-grid-enterprise-4.1.4.tgz
npm http 404 https://registry.npmjs.org/angular/core/2.0.0-rc.1
npm http 404 https://registry.npmjs.org/angular/router-deprecated/2.0.0-rc.1
npm http 404 https://registry.npmjs.org/angular/platform-browser-dynamic/2.0.0-rc.1
npm http 404 https://registry.npmjs.org/angular/upgrade/2.0.0-rc.1

This is a fresh git clone as of 
Latest commit bad5317 15 days ago (that would be

https://github.com/ceolter/ag-grid-ng2-example/commit/bad53178cad96694141844fa77c3caf7a24cce6f )

**Comment by seanlandsman** [comment]
I assume that this is no longer an issue - please raise a new issue if this is still a problem for you.

**Comment by kbommalingaiah** [comment]
Hi 
I am installing ag-grid-angular  in angular cli 8
getting issue
